import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "mantine-react-table/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { PageLayout } from "@/components/Layout/PageLayout";
import { theme } from "../theme";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mess Managed",
  description: "Generated by create next app",
  manifest: "./manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <meta
          name="viewport"
          content="minium-scale=1, initial-scale=1, width=device-width"
        />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <PageLayout>{children}</PageLayout>
        </MantineProvider>
      </body>
    </html>
  );
}
